from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from lib.config import load_config
from lib.sections import discover_sections
from lib.sync_state import detect_conflict, update_section_state, file_hash

_HARNESS_ROOT = Path(__file__).parent.parent.parent


def _check_pandoc() -> bool:
    try:
        subprocess.run(["pandoc", "--version"], capture_output=True, check=True)
        return True
    except (FileNotFoundError, subprocess.CalledProcessError):
        return False


def _compile_abstract(md_path: Path) -> str:
    """Strip # heading + HTML comments, compile body through pandoc, wrap in abstract env."""
    content = md_path.read_text()
    body_lines = [l for l in content.splitlines() if not l.strip().startswith("# ")]
    body = re.sub(r"<!--.*?-->", "", "\n".join(body_lines), flags=re.DOTALL).strip()
    if not body:
        return "\\begin{abstract}\n\\end{abstract}\n"
    result = subprocess.run(
        ["pandoc", "--no-standalone", "--from", "markdown", "--to", "latex"],
        input=body, capture_output=True, text=True, check=True,
    )
    return f"\\begin{{abstract}}\n{result.stdout.strip()}\n\\end{{abstract}}\n"


def _compile_section_to_tex(md_path: Path, citation_package: str) -> str:
    """Compile a section .md to LaTeX using natbib or biblatex citation mode."""
    result = subprocess.run(
        [
            "pandoc", "--no-standalone",
            "--from", "markdown",
            "--to", "latex",
            f"--{citation_package}",
            str(md_path),
        ],
        capture_output=True, text=True, check=True,
    )
    return result.stdout


def _write_harness_inputs(dest_dir: Path, section_stems: list[str]) -> Path:
    """Write/update harness-inputs.tex with \\input commands for each stem."""
    out = dest_dir / "harness-inputs.tex"
    lines = ["% Auto-generated by /paper:deploy — do not edit manually\n"]
    for stem in section_stems:
        lines.append(f"\\input{{sections/{stem}}}\n")
    out.write_text("".join(lines))
    return out


def _compile_word(
    sections: list,
    out_path: Path,
    bib_path: Path,
    csl_path: Path,
) -> None:
    """Concatenate all section .md files and compile to .docx via pandoc stdin."""
    combined = "\n\n".join(p.read_text() for _, _, p in sections)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "pandoc", "--standalone",
        "--from", "markdown",
        "--to", "docx",
        "--output", str(out_path),
        "-",
    ]
    if bib_path.exists():
        cmd += ["--citeproc", f"--bibliography={bib_path}", f"--csl={csl_path}"]
    subprocess.run(cmd, input=combined, capture_output=True, text=True, check=True)


def run(root: Path = _HARNESS_ROOT) -> dict:
    """Compile all sections. Returns summary dict or {} on unrecoverable error."""
    if not _check_pandoc():
        print("pandoc not found. Install: https://pandoc.org/installing.html")
        return {}

    config = load_config(root)
    article_dir = root / "article"
    bib_path = root / "research" / "candidates.bib"
    state_path = article_dir / "sync-state.json"

    sections = discover_sections(article_dir, exclude=config.exclude_sections)
    if not sections:
        print("No sections found in article/sections/")
        return {}

    if config.target == "word":
        csl_path = article_dir / "csl" / config.csl
        if not csl_path.exists():
            csl_path = root / "_harness" / "templates" / "csl" / config.csl
        out_path = article_dir / "output" / "paper.docx"
        try:
            _compile_word(sections, out_path, bib_path, csl_path)
            print(f"Word output: {out_path}")
        except subprocess.CalledProcessError as e:
            print(f"pandoc error: {e.stderr[:300]}")
            return {}
        return {
            "compiled": len(sections),
            "conflicts": [],
            "target": "word",
            "output": str(out_path),
        }

    # Overleaf target
    if not config.overleaf_repo:
        print("overleaf_repo not set in paper.yaml. Add the path to your cloned Overleaf repo.")
        return {}

    overleaf = Path(config.overleaf_repo).expanduser().resolve()
    if not overleaf.exists():
        print(f"Overleaf repo not found at: {overleaf}")
        return {}

    tex_dir = overleaf / "sections"
    tex_dir.mkdir(exist_ok=True)

    compiled: list[str] = []
    conflicts: list[str] = []

    for _, stem, md_path in sections:
        tex_path = tex_dir / f"{stem}.tex"

        if detect_conflict(stem, md_path, tex_path, state_path):
            print(f"  CONFLICT {stem}: both .md and .tex changed since last sync — skipping")
            conflicts.append(stem)
            continue

        try:
            if stem == "10_abstract":
                tex_content = _compile_abstract(md_path)
            else:
                tex_content = _compile_section_to_tex(md_path, config.citation_package)
            tex_path.write_text(tex_content)
            update_section_state(stem, file_hash(md_path), file_hash(tex_path), state_path)
            compiled.append(stem)
            print(f"  compiled: {stem}.tex")
        except subprocess.CalledProcessError as e:
            print(f"  ERROR compiling {stem}: {e.stderr[:200]}")

    if bib_path.exists():
        shutil.copy(bib_path, overleaf / "references.bib")
        print(f"  copied: references.bib")

    figures_src = article_dir / "figures"
    if figures_src.exists():
        figures_dst = overleaf / "figures"
        figures_dst.mkdir(exist_ok=True)
        for fig in figures_src.iterdir():
            if fig.is_file() and not fig.name.startswith("."):
                shutil.copy(fig, figures_dst / fig.name)

    stems_with_tex = [
        stem for _, stem, _ in sections
        if (tex_dir / f"{stem}.tex").exists()
    ]
    _write_harness_inputs(overleaf, stems_with_tex)

    return {
        "compiled": len(compiled),
        "conflicts": conflicts,
        "target": "overleaf",
        "overleaf_repo": str(overleaf),
    }


if __name__ == "__main__":
    result = run()
    if not result:
        sys.exit(1)
